version: "3.8"

networks:
    network-backend:
        driver: bridge

services:
    backend:
        container_name: backend
        build: ./api/
        restart: always
        ports:
            - "5000:5000"
        environment:
            - NODE_ENV=DOCKER
            - NODE_IN_MEMORY=TRUE
            
