
export enum overlayIconEnum {
	Remove =
		'fas fa-backspace',
	BagCheckout =
		'fas fa-shopping-cart',
	BagCart =
		'fas fa-shopping-bag',
	PaymentPayBal =
		'fab fa-cc-paypal',
	PaymentStripe =
		'fab fa-cc-stripe',
	PaymentVisa =
		'fab fa-cc-visa',
	PaymentMasterCard =
		'fab fa-cc-mastercard',
	SocialFacebookSquare =
		'fab fa-facebook-square',
	SocialPinterest =
		'fab fa-pinterest-p',
	SocialFacebook =
		'fab fa-facebook-f',
	SocialTwitter =
		'fab fa-twitter',
	SocialInstagram =
		'fab fa-instagram',
	ShowGrid =
		'fas fa-th',
	ShowList =
		'fas fa-align-justify',
	Close =
		'fas fa-times',
	UserLock =
		'fas fa-lock',
	UserUnlock =
		'fas fa-lock-open',
	ToggleOff =
		'fas fa-toggle-off',
	ToggleOn =
		'fas fa-toggle-on',
	LeftDouble =
		'fas fa-angle-double-left',
	LeftSingle =
		'fas fa-angle-left',
	RightDouble =
		'fas fa-angle-double-right',
	RightSingle =
		'fas fa-angle-right',
	StarEmpty =
		'far fa-star',
	StarFull =
		'fas fa-star',
	Save =
		'far fa-save',
	Details =
		'fas fa-chevron-right',
	Edit =
		'far fa-edit',
	Delete =
		'fas fa-trash-alt',
	Plus =
		'fas fa-plus',
	Minus =
		'fas fa-minus',
	Filter =
		'fas fa-filter',
	EditUser =
		'fas fa-user-edit',
	EditPassword =
		'fas fa-key',
	SignOut =
		'fas fa-sign-out-alt',
	CollapserDown =
		'fas fa-caret-down',
	CollapserUp =
		'fas fa-caret-up',
	Comment =
		'far fa-comment-alt',
	Calendar =
		'far fa-calendar-alt',
	Ellipsis =
		'fas fa-ellipsis-h',
	Search =
		'fab fa-sistrix',
}

